### ISSUE TITLE
Build phase triggers "extraneous input" error

### ISSUE THREAD

**Issue by dnicolson** [Karumi/Kin#48]
Running Kin against this [project](https://github.com/Provenance-Emu/Provenance/blob/a45d68c5b37098c58ae9c09e7df688379ff86656/Provenance.xcodeproj/project.pbxproj) causes the following errors:

```
ERROR: line 1868:4 extraneous input '6W8N7WB7Z36QWEFVAW5LHTNV' expecting {')', REFERENCE}
ERROR: line 1892:4 extraneous input '0CO5J70NW5JDTTZ5BCHAVYZE' expecting {';', ')', 'buildRules', 'rootObject', REFERENCE}
ERROR: line 1914:4 extraneous input '6OBYKZXD36MCSZYQLYVIY1AY' expecting {';', ')', 'buildRules', 'rootObject', REFERENCE}
ERROR: line 2125:2 extraneous input '0CO5J70NW5JDTTZ5BCHAVYZE' expecting REFERENCE
ERROR: line 2191:2 extraneous input '6OBYKZXD36MCSZYQLYVIY1AY' expecting REFERENCE
```

The project has been updated with Xcode 12.2 (12B45b) so it is expected to be valid.

**Comment by Serchinastico** [comment]
Hi @dnicolson,

This is most probably because the pbxproj format has been updated or we didn't capture those scenarios in the first place. We'd need to:

1. Update the grammar
2. Add the offending `project.pbxproj` file as a test
3. Release a new version of Kin.

 I'll raise a PR addressing the two first points and let the Karumi team release a new version when they have time.

Thank you so much for the report!

**Comment by pedrovgs** [comment]
Than you so much @Serchinastico 😃 you rock! I've already reviewed and merged your PR. Could you please @davideme release a new version?

**Comment by davideme** [comment]
Sure, I'll add it to my list!

**Comment by pedrovgs** [comment]
Thanks!
